apiVersion: v2
name: azure-private-endpoint-operator
version: 0.4.0-dev
appVersion: 0.4.0-dev
description: Operator for reconciling Azure Private Links in CAPZ workload clusters to Azure Private Endpoints in CAPZ management clusters
home: https://github.com/giantswarm/azure-private-endpoint-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
  io.giantswarm.application.team: phoenix
  config.giantswarm.io/version: 1.x.x
